//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COPD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messdaten
    {
        public int Id { get; set; }
        public int FK_MesstypID { get; set; }
        public int FK_PatientID { get; set; }
    
        public virtual Patienten Patienten { get; set; }
        public virtual Messtypen Messtypen { get; set; }
    }
}
